version: "3.3"

services:
  db:
    container_name: itemsdb
    restart: unless-stopped
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./internal/item/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
